name: Build and deploy ASP.NET Core to Azure Web App - api-test-5542

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_PATH: test_AxelRivera.WebApi/test_AxelRivera.WebApi.csproj
  PUBLISH_DIR: publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build (Release)
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_DIR }} --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-package
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-package
          path: ./publish

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2B6EC67FFE54ED8B61014569804AEA3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_977398E8D76C4D099631338F11B95D44 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FF0F1A0DD96240D29FE1A9DA726A254E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: api-test-5542
          slot-name: Production
          package: ./publish
